import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, FileText } from "lucide-react";

const pages: Record<string, { title: string; intro: string; sections: { title: string; text: string }[] }> = {
  acerca: { title: "Acerca de Claro", intro: "Herramientas sencillas para resolver preguntas cotidianas.", sections: [{ title: "Una pequeña ayuda para tu día", text: "Claro reúne calculadoras y conversores que puedes usar sin crear una cuenta. Cada herramienta incluye una explicación del cálculo, ejemplos y sus límites para que entiendas el resultado." }, { title: "Un proyecto en preparación", text: "Claro es el nombre provisional del proyecto. La identificación del titular, los datos de contacto y la información jurídica están pendientes de completar antes del lanzamiento definitivo." }] },
  metodologia: { title: "Nuestra metodología", intro: "Un resultado es más útil cuando sabes de dónde viene.", sections: [{ title: "Cálculos que se pueden entender", text: "Las herramientas utilizan fórmulas explícitas y muestran la metodología junto al resultado. Los ejemplos ayudan a comprobar cómo se aplica el cálculo a una situación concreta." }, { title: "Alcance y precisión", text: "Cada herramienta indica sus límites. Los resultados pueden redondearse para facilitar su lectura; la precisión visible depende del cálculo. Consulta siempre el apartado «Ten en cuenta» antes de usar una respuesta." }, { title: "Datos en tu dispositivo", text: "Las herramientas de esta versión realizan los cálculos en el navegador. No es necesario registrarse para utilizarlas. Los valores introducidos no se guardan en el catálogo." }, { title: "Revisión editorial pendiente de formalización", text: "La política editorial definitiva, la identidad de la persona responsable y el canal para comunicar errores deben completarse antes del lanzamiento. Estas herramientas iniciales cubren porcentajes, fechas y conversiones de longitud." }] },
  contacto: { title: "Contacto", intro: "Queremos que puedas comunicar una duda o un error con facilidad.", sections: [{ title: "Canal de contacto pendiente", text: "El titular todavía debe configurar un correo o formulario de contacto y publicar sus datos. Esta página no dispone por ahora de un canal de envío activo." }, { title: "Si detectas un cálculo incorrecto", text: "Conserva el nombre de la herramienta, los valores introducidos y el resultado que esperabas. Esa información permitirá reproducir el problema cuando esté disponible el canal de contacto. Evita incluir información personal sensible." }] },
  privacidad: { title: "Política de privacidad", intro: "Documento provisional pendiente de revisión y de los datos del titular.", sections: [{ title: "Funcionamiento de las herramientas", text: "Los cálculos públicos de esta versión se realizan en tu navegador. No requieren una cuenta. Los valores que introduces no se envían a una base de datos para realizar el cálculo." }, { title: "Información pendiente", text: "Antes de publicar una política definitiva deben identificarse el responsable del tratamiento, sus datos de contacto, los proveedores utilizados, las finalidades y bases jurídicas aplicables, los plazos de conservación y el procedimiento para ejercer derechos." }, { title: "Servicios adicionales", text: "La información sobre registros técnicos del alojamiento, acceso al área de administración y cualquier servicio de analítica o publicidad debe concretarse según la configuración real del sitio. Este borrador no sustituye una política de privacidad completa." }] },
  cookies: { title: "Política de cookies", intro: "Documento provisional: debe ajustarse a los servicios que se activen en el sitio.", sections: [{ title: "Uso público de las herramientas", text: "El cálculo de las herramientas no necesita guardar los valores en cookies. El acceso al área de administración puede utilizar cookies para mantener una sesión autenticada." }, { title: "Analítica, publicidad y consentimiento", text: "Antes de activar servicios que requieran consentimiento, el titular debe identificar sus cookies y finalidades, publicar sus duraciones y proveedores, e incorporar el mecanismo de consentimiento correspondiente." }, { title: "Inventario pendiente", text: "La lista definitiva de cookies y las instrucciones para cambiar las preferencias deben comprobarse con la configuración de producción. Este documento sigue pendiente de completar y revisar." }] },
  terminos: { title: "Condiciones de uso", intro: "Borrador pendiente de los datos del titular y de revisión para la jurisdicción aplicable.", sections: [{ title: "Uso de las herramientas", text: "Las calculadoras y los conversores ofrecen resultados informativos a partir de los valores que introduces. Revisa las unidades, las hipótesis y los límites indicados en cada herramienta." }, { title: "Comprobación de resultados", text: "Los resultados pueden contener redondeos o depender de condiciones simplificadas. Si vas a utilizar una cifra en una decisión importante, comprueba el cálculo y su adecuación a tu caso." }, { title: "Condiciones pendientes de completar", text: "Deben definirse la identidad y el domicilio del titular, el contacto, las reglas de uso, los derechos de propiedad intelectual y el régimen jurídico aplicable antes de considerar este documento definitivo." }] },
};

type Props = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return Object.keys(pages).map((slug) => ({ slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; return { title: pages[slug]?.title ?? "Página no encontrada", robots: { index: false, follow: true } }; }

export default async function LegalPage({ params }: Props) {
  const { slug } = await params;
  const page = pages[slug];
  if (!page) notFound();
  return <div className="container legal-page"><Link className="back-link" href="/"><ArrowLeft size={15} aria-hidden="true" />Inicio</Link><header><span className="eyebrow">El proyecto, con claridad</span><h1>{page.title}</h1><p className="page-description">{page.intro}</p></header><div className="notice"><FileText size={20} aria-hidden="true" /><div><strong>Documento provisional</strong><p>Pendiente de completar y revisar por el titular antes del lanzamiento definitivo.</p></div></div><div className="legal-content">{page.sections.map((section) => <section key={section.title}><h2>{section.title}</h2><p>{section.text}</p></section>)}</div><nav className="legal-links" aria-label="Más información sobre el proyecto">{Object.entries(pages).filter(([key]) => key !== slug).map(([key, page]) => <Link href={`/legal/${key}`} key={key}>{page.title}</Link>)}</nav></div>;
}
