import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { categories, seedTools } from "../src/lib/tools/seeds";

const literal = (value: string) => `'${value.replaceAll("'", "''")}'`;
const sql = [
  "-- Generated by npm run db:seed:sql. Do not edit; source is src/lib/tools/seeds.ts.",
  "-- Idempotent insert: existing tools and edited content are preserved.",
  "begin;",
  ...categories.map((category, index) => `insert into public.categories (slug, name, description, sort_order) values (${literal(category.slug)}, ${literal(category.name)}, ${literal(category.description)}, ${index}) on conflict (slug) do nothing;`),
  ...seedTools.map((tool) => {
    const json = JSON.stringify(tool);
    const hash = createHash("sha256").update(json).digest("hex");
    return `with new_tool as (
  insert into public.tool_definitions (slug, title, short_description, category_slug, status, current_version, is_indexable, is_monetizable, published_at)
  values (${literal(tool.slug)}, ${literal(tool.title)}, ${literal(tool.shortDescription)}, ${literal(tool.category)}, 'published', ${tool.version}, true, false, now())
  on conflict (slug) do nothing returning id
), new_version as (
  insert into public.tool_versions (tool_id, version, definition, content_hash, change_summary)
  select id, ${tool.version}, ${literal(json)}::jsonb, ${literal(hash)}, 'Herramienta inicial validada' from new_tool
  returning tool_id
)
insert into public.audit_log (entity_type, entity_id, action, next_state, actor_type, message)
select 'tool', tool_id, 'seed.published', 'published', 'system', 'Versión inicial del primer hito' from new_version;`;
  }),
  "commit;",
  "",
].join("\n\n");

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql, "utf8");
console.log(`Generated supabase/seed.sql with ${seedTools.length} tools.`);
